# Generated by Django 5.1 on 2024-09-30 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='cast_member',
            new_name='cast_members',
        ),
        migrations.AddField(
            model_name='video',
            name='banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner', to='video.imagemedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail', to='video.imagemedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_half',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail_half', to='video.imagemedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_trailer', to='video.audiovideomedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_media', to='video.audiovideomedia'),
        ),
    ]
