# Generated by Django 5.1 on 2024-10-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_cast_member_video_cast_members_video_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiovideomedia',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='imagemedia',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='imagemedia',
            name='raw_location',
        ),
        migrations.AddField(
            model_name='audiovideomedia',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('TRAILER', 'TRAILER')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemedia',
            name='location',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='imagemedia',
            name='type',
            field=models.CharField(choices=[('THUMBNAIL_HALF', 'THUMBNAIL_HALF'), ('THUMBNAIL', 'THUMBNAIL'), ('BANNER', 'BANNER')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
