# Generated by Django 5.1 on 2024-10-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_audiovideomedia_checksum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemedia',
            name='location',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='video',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_half',
        ),
        migrations.RemoveField(
            model_name='video',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='banner',
            field=models.ManyToManyField(blank=True, null=True, related_name='banner', to='video.imagemedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ManyToManyField(blank=True, null=True, related_name='video_thumbnail', to='video.imagemedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_half',
            field=models.ManyToManyField(blank=True, null=True, related_name='video_thumbnail_half', to='video.imagemedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='trailer',
            field=models.ManyToManyField(blank=True, null=True, related_name='video_trailer', to='video.audiovideomedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, related_name='video_media', to='video.audiovideomedia'),
        ),
    ]
