# Generated by Django 5.1 on 2024-10-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovideomedia',
            name='raw_location',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
