# Generated by Django 5.1 on 2024-10-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_audiovideomedia_raw_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovideomedia',
            name='raw_location',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, related_name='video_media', to='video.audiovideomedia'),
        ),
    ]
