# Generated by Django 5.1 on 2024-10-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_remove_video_video_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_half',
        ),
        migrations.RemoveField(
            model_name='video',
            name='trailer',
        ),
        migrations.AddField(
            model_name='video',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner', to='video.imagemedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail', to='video.imagemedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_half',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail_half', to='video.imagemedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_trailer', to='video.audiovideomedia'),
        ),
    ]
