# Generated by Django 5.1 on 2024-10-13 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_remove_video_banner_remove_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='video.imagemedia'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_thumbnail', to='video.imagemedia'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_half',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_thumbnail_half', to='video.imagemedia'),
        ),
        migrations.AlterField(
            model_name='video',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_trailer', to='video.audiovideomedia'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_media', to='video.audiovideomedia'),
        ),
    ]
