# Generated by Django 5.1 on 2024-08-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_descripton_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated_date',
            field=models.DateField(default=None),
        ),
    ]
