# Generated by Django 5.1 on 2024-08-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
