# Generated by Django 5.1 on 2024-08-25 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='createed_date',
        ),
        migrations.AddField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
