# Generated by Django 5.1 on 2024-09-04 21:59

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0005_remove_category_createed_date_category_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_date', models.DateTimeField(default=None, null=True)),
                ('categories', models.ManyToManyField(related_name='genres', to='category.category')),
            ],
            options={
                'db_table': 'genres',
            },
        ),
    ]
